### PR TITLE
update for actix-web 4.0.0-beta.3

### PR DESCRIPTION
**Pull request by rich-murphey**
I have done very limited testing of these changes with app using actix-web 4.0.0-beta.3.

### CODE REVIEW

**Comment by kilork** [comment]
Thank you! Do we need to rush with this before actix-web would be stable? I once tried to match even alpha version, but now I am not sure.

**Comment by rich-murphey** [comment]
Hey, sorry for the delay. Yes, I see other crates like tokio and actix successfully releasing semver compatible names like  0.2.0-beta.1 that do not 'cargo update' from 0.1.1.  But I don't have any direct experience doing releases, so I'm unsure in practice.  Either way, no rush.  Use whatever portions if any of this you find useful.  I'm continuing to build daily using this branch, with toio 1, actix-web beta and the current stable sqlx branch.  So I can update this branch if I see  any new issues come up.

**Comment by kilork** [comment]
I think, we will release 3.1, and then would use your changes to migrate to the version of actix-web, which would be at this moment latest. Hopefully they would be stable really soon, depending on beta is more work each time, because we cannot just say actix-web = "4", we need to write exact version and then repeat this more times in the documentation. This makes feature development for crate with beta dependency a little bit tricky and for those depending on this - more tricky to do update, than just to run `cargo update`. But because I also really want to switch all my dependencies to tokio="1" beta variant still can be a good solution, we will see.

**Comment by rich-murphey** [comment]
Ok, sounds good!  I'll try to keep this in sync with kilork:master and update for any changes in actix-web versions.

**Comment by MarinPostma** [comment]
hey! I have a branch patched for [beta6 here](https://github.com/MarinPostma/actix-web-static-files/tree/actix-web-4). Feel free to use it :)

**Comment by kilork** [comment]
Sorry @MarinPostma, just saw your comment, I am still waiting for stable release and working hard on the next release of `actix-web-static-files` itself. Hopefully both happen soon and we will merge all of current contributions to the `4.x` version of the `actix-web-static-files`.

**Pull request closed without merging**
